name: Format Check

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: ./.github/actions/setup-go
        with:
          go-version: '1.23.6'

      - name: Check formatting
        run: |
          for dir in . compiler runtime; do
            pushd $dir
            if [ -n "$(go fmt ./...)" ]; then
              echo "Some files are not properly formatted. Please run 'go fmt ./...'"
              exit 1
            fi
            popd
          done
          echo "All files are properly formatted."
